# Attach info to any `PaperTrail::Version`s generated by this job about the
# job that generated them
Delayed::Worker.lifecycle.around(:invoke_job) do |job, &block|
  PaperTrailUtils.with_metadata(delayed_job: { id: job.id, tag: job.tag }) do
    block.call(job)
  end
end
