# Attach info to any `PaperTrail::Version`s generated by this job about the
# job that generated them
Delayed::Worker.lifecycle.around(:invoke_job) do |job, &block|
  PaperTrail.request.controller_info = {
    metadata: {
      delayed_job: {
        id: job.id,
        tag: job.tag
      }
    }
  }

  begin
    block.call(job)
  ensure
    PaperTrail.request.controller_info = nil
  end
end
