development:
  adapter: redis
  url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379/5' %>
  channel_prefix: heimdall_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: heimdall_production
