# == Schema Information
#
# Table name: inventory_bins
#
#  id                :bigint           not null, primary key
#  notes             :text
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  inventory_area_id :bigint
#  inventory_item_id :bigint
#
# Indexes
#
#  index_inventory_bins_on_inventory_area_id  (inventory_area_id)
#  index_inventory_bins_on_inventory_item_id  (inventory_item_id)
#

class InventoryBin < ApplicationRecord
  has_paper_trail

  belongs_to :inventory_area

  belongs_to :inventory_item, optional: true

  before_create do
    # Use a counter to assign IDs so that we don't skip IDs when rolling back
    # transactions and so that all IDs generated from within a single
    # transaction (including those generated by attemps to create a batch of
    # bins at once) are sequential.
    self.id = Counter.next('inventory_bin_ids')
  end

  def display_name
    contents = "(#{inventory_item.name}) - " if inventory_item
    "Bin ##{id} - #{contents}[#{inventory_area.name}]"
  end

  def as_json(options = {})
    super.merge(display_name: display_name)
  end
end
